### ISSUE TITLE
大佬,你的emby开心版我安装报错是怎么回事,我是openwrt,arm64的系统

### ISSUE THREAD

**Issue by coder2008** [LOVEChen/LOVEAPISecret#1]
![微信图片_20230127103354](https://user-images.githubusercontent.com/31384415/214998227-e627039c-6d6d-44da-8f15-9525338b9954.png)

**Comment by coder2008** [comment]
Error Main: Error in appHost.Init
        *** Error Report ***
        Version: 4.7.10.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 5.9.8-flippy-49+ (root@x96-max) (gcc (Debian 8.3.0-6) 8.3.0, GNU ld (GNU Binutils for Debian) 2.31.1) #31 SMP PREEMPT Thu Nov 12 17:15:3
        Framework: .NET 6.0.8
        OS/Process: arm64/arm64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        System.BadImageFormatException: System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Server.Kestrel.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. An attempt was made to load a program with an incorrect format.

        File name: 'Microsoft.AspNetCore.Server.Kestrel.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
           at Emby.Server.Implementations.HttpServer.KestrelHost.KestrelListener.OnAddPrefixesComplete()
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.OnAddPrefixesComplete()
           at Emby.Server.Implementations.ApplicationHost.Init()
           at EmbyServer.HostedService.StartAsync(CancellationToken cancellationToken)
        Source: EmbyServer
        TargetSite: Void OnAddPrefixesComplete()
